import { useState, useEffect, useCallback } from "react";
import { Link, useNavigate } from "react-router-dom";
import { Button } from "@/components/ui/button";
import Logo from "@/components/Logo";
import { useAuth } from "@/contexts/AuthContext";
import { useCredits } from "@/hooks/useCredits";
import { useProjects } from "@/hooks/useProjects";
import {
  Plus,
  FolderOpen,
  Clock,
  Download,
  MoreVertical,
  LogOut,
  Settings,
  User,
  CreditCard,
  Loader2,
  Apple,
  Play,
  Rocket,
  FileUp,
  ExternalLink,
  Trash2,
  Code,
  Server,
  Package,
  Check,
  Sparkles,
  RefreshCw,
} from "lucide-react";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from "@/components/ui/alert-dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { toast } from "sonner";
import { Progress } from "@/components/ui/progress";
import { 
  Project, 
  getAppTypeLabel, 
  getAppTypeIcon,
  getBuildStatus,
  downloadReactNativeCode,
  downloadBackendCode,
  downloadCompletePackage,
  deleteProject,
} from "@/services/projects";

const FEATURE_LABELS: Record<string, string> = {
  login: 'Auth',
  payment: 'Payment',
  maps: 'Maps',
  notifications: 'Push',
  chat: 'Chat',
  search: 'Search',
  favorites: 'Wishlist',
  reviews: 'Reviews',
  analytics: 'Analytics',
  'social-share': 'Share',
};

const Dashboard = () => {
  const navigate = useNavigate();
  const { user, signOut } = useAuth();
  const { balance, isLoading: creditsLoading } = useCredits();
  const { projects, completedProjects, buildingProjects, isLoading: projectsLoading, refetch } = useProjects();
  const [figmaDialogOpen, setFigmaDialogOpen] = useState(false);
  const [figmaUrl, setFigmaUrl] = useState("");
  const [deleteDialogOpen, setDeleteDialogOpen] = useState(false);
  const [projectToDelete, setProjectToDelete] = useState<Project | null>(null);
  const [isDeleting, setIsDeleting] = useState(false);

  // Poll building projects for status updates
  useEffect(() => {
    if (buildingProjects.length === 0) return;

    const pollInterval = setInterval(async () => {
      for (const project of buildingProjects) {
        try {
          const status = await getBuildStatus(project.id);
          if (status.status === 'completed' || status.status === 'failed') {
            refetch();
          }
        } catch (error) {
          console.error('Failed to poll status:', error);
        }
      }
    }, 3000);

    return () => clearInterval(pollInterval);
  }, [buildingProjects, refetch]);

  const handleSignOut = async () => {
    await signOut();
    toast.success("Signed out successfully");
    navigate("/signin");
  };

  const handleFigmaImport = () => {
    if (!figmaUrl.trim()) {
      toast.error("Please enter a Figma URL");
      return;
    }
    toast.info("Figma import feature coming soon!");
    setFigmaDialogOpen(false);
    setFigmaUrl("");
  };

  const handleDownloadReactNative = async (project: Project) => {
    try {
      toast.info(`Preparing React Native code for ${project.name}...`);
      const url = await downloadReactNativeCode(project.id);
      window.open(url, '_blank');
      toast.success('Download started!');
    } catch (error) {
      toast.error('Download not available yet. Try the mock download.');
      // Mock download for demo
      const content = `// ${project.name} - React Native Code\n// Generated by AppDev\n\nexport default function App() {\n  return <View><Text>Hello ${project.name}!</Text></View>;\n}`;
      const blob = new Blob([content], { type: 'text/plain' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `${project.name}-react-native.txt`;
      a.click();
      URL.revokeObjectURL(url);
    }
  };

  const handleDownloadBackend = async (project: Project) => {
    try {
      toast.info(`Preparing backend code for ${project.name}...`);
      const url = await downloadBackendCode(project.id);
      window.open(url, '_blank');
      toast.success('Download started!');
    } catch (error) {
      toast.error('Download not available yet. Try the mock download.');
      // Mock download for demo
      const content = `// ${project.name} - Backend Code\n// Generated by AppDev\n\nconst express = require('express');\nconst app = express();\n\napp.listen(3001, () => console.log('${project.name} backend running'));`;
      const blob = new Blob([content], { type: 'text/plain' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `${project.name}-backend.txt`;
      a.click();
      URL.revokeObjectURL(url);
    }
  };

  const handleDownloadComplete = async (project: Project) => {
    try {
      toast.info(`Preparing complete package for ${project.name}...`);
      const url = await downloadCompletePackage(project.id);
      window.open(url, '_blank');
      toast.success('Download started!');
    } catch (error) {
      toast.error('Download not available yet');
    }
  };

  const handleOpenExpoSnack = (project: Project) => {
    if (project.snackUrl) {
      window.open(project.snackUrl, '_blank');
    } else {
      const encodedName = encodeURIComponent(project.name);
      window.open(`https://snack.expo.dev/?name=${encodedName}&platform=ios`, '_blank');
      toast.info('Opening Expo Snack - paste your code to preview');
    }
  };

  const handleDeleteProject = async () => {
    if (!projectToDelete) return;
    
    setIsDeleting(true);
    try {
      await deleteProject(projectToDelete.id);
      toast.success(`${projectToDelete.name} deleted successfully`);
      refetch();
    } catch (error) {
      toast.error('Failed to delete project');
    } finally {
      setIsDeleting(false);
      setDeleteDialogOpen(false);
      setProjectToDelete(null);
    }
  };

  const confirmDelete = (project: Project) => {
    setProjectToDelete(project);
    setDeleteDialogOpen(true);
  };

  const getStatusBadge = (project: Project) => {
    const styles: Record<string, string> = {
      completed: "bg-green-500/10 text-green-500 border-green-500/20",
      building: "bg-yellow-500/10 text-yellow-500 border-yellow-500/20",
      draft: "bg-muted text-muted-foreground border-border",
      failed: "bg-red-500/10 text-red-500 border-red-500/20",
    };
    const labels: Record<string, string> = {
      completed: "Ready",
      building: project.progress ? `${project.progress}%` : "Building...",
      draft: "Draft",
      failed: "Failed",
    };
    return (
      <span className={`text-xs px-2 py-1 rounded-full border ${styles[project.status] || styles.draft}`}>
        {project.status === 'building' && <Loader2 className="w-3 h-3 inline mr-1 animate-spin" />}
        {project.status === 'completed' && <Check className="w-3 h-3 inline mr-1" />}
        {labels[project.status] || project.status}
      </span>
    );
  };

  const getUserInitials = () => {
    if (!user?.name) return "U";
    return user.name
      .split(" ")
      .map((n) => n[0])
      .join("")
      .toUpperCase()
      .slice(0, 2);
  };

  const renderEmptyState = () => (
    <div className="col-span-full flex flex-col items-center justify-center py-16 text-center">
      <div className="w-20 h-20 rounded-2xl bg-gradient-primary/10 flex items-center justify-center mb-6">
        <Sparkles className="w-10 h-10 text-primary" />
      </div>
      <h3 className="text-xl font-semibold text-foreground mb-2">No apps yet</h3>
      <p className="text-muted-foreground mb-6 max-w-sm">
        Start building your first mobile app with AI. Just describe your idea and we'll generate the code.
      </p>
      <Button variant="gradient" onClick={() => navigate("/builder")} className="gap-2">
        <Plus className="w-4 h-4" />
        Create Your First App
      </Button>
    </div>
  );

  const renderProjectCard = (project: Project) => (
    <div
      key={project.id}
      className="group p-5 rounded-xl border border-border bg-card/30 hover:border-primary/50 hover:bg-card/50 transition-all animate-fade-in"
    >
      <div className="flex items-start justify-between mb-3">
        <div className="flex items-center gap-3">
          <div className="w-12 h-12 rounded-xl bg-muted flex items-center justify-center text-2xl">
            {getAppTypeIcon(project.appType)}
          </div>
          <div>
            <h3 className="font-semibold text-foreground">{project.name}</h3>
            <p className="text-xs text-muted-foreground">{getAppTypeLabel(project.appType)}</p>
          </div>
        </div>
        <DropdownMenu>
          <DropdownMenuTrigger asChild>
            <Button
              variant="ghost"
              size="icon"
              className="opacity-0 group-hover:opacity-100 transition-opacity"
            >
              <MoreVertical className="w-4 h-4" />
            </Button>
          </DropdownMenuTrigger>
          <DropdownMenuContent align="end">
            <DropdownMenuItem onClick={() => navigate(`/builder?project=${project.id}`)}>
              Open in Builder
            </DropdownMenuItem>
            <DropdownMenuItem>Duplicate</DropdownMenuItem>
            <DropdownMenuSeparator />
            <DropdownMenuItem 
              onClick={() => confirmDelete(project)} 
              className="text-destructive"
            >
              <Trash2 className="w-4 h-4 mr-2" />
              Delete
            </DropdownMenuItem>
          </DropdownMenuContent>
        </DropdownMenu>
      </div>

      <p className="text-sm text-muted-foreground mb-3 line-clamp-2">{project.description}</p>
      
      {/* Theme Colors */}
      <div className="flex items-center gap-2 mb-3">
        <span className="text-xs text-muted-foreground">Theme:</span>
        <div className="flex gap-1">
          <div 
            className="w-5 h-5 rounded-full border border-border" 
            style={{ backgroundColor: project.theme.primary }}
            title="Primary"
          />
          <div 
            className="w-5 h-5 rounded-full border border-border" 
            style={{ backgroundColor: project.theme.secondary }}
            title="Secondary"
          />
          <div 
            className="w-5 h-5 rounded-full border border-border" 
            style={{ backgroundColor: project.theme.accent }}
            title="Accent"
          />
        </div>
      </div>

      {/* Features */}
      <div className="flex flex-wrap gap-1 mb-3">
        {project.features.slice(0, 4).map((feature) => (
          <span 
            key={feature} 
            className="text-[10px] px-1.5 py-0.5 rounded bg-primary/10 text-primary"
          >
            {FEATURE_LABELS[feature] || feature} ✓
          </span>
        ))}
        {project.features.length > 4 && (
          <span className="text-[10px] px-1.5 py-0.5 rounded bg-muted text-muted-foreground">
            +{project.features.length - 4} more
          </span>
        )}
      </div>

      <div className="flex items-center justify-between mb-4">
        {getStatusBadge(project)}
        <span className="text-xs text-muted-foreground">
          {new Date(project.createdAt).toLocaleDateString()}
        </span>
      </div>

      {/* Building progress */}
      {project.status === "building" && (
        <div className="mb-4">
          <Progress value={project.progress || 50} className="h-2" />
          <p className="text-xs text-muted-foreground mt-1">
            {project.currentStep || 'Building your app...'}
          </p>
        </div>
      )}

      {/* Failed status */}
      {project.status === "failed" && (
        <div className="mb-4 p-2 rounded bg-red-500/10 border border-red-500/20">
          <p className="text-xs text-red-500">
            Build failed. Try regenerating or contact support.
          </p>
          <Button 
            variant="outline" 
            size="sm" 
            className="mt-2 w-full gap-1"
            onClick={() => navigate(`/builder?project=${project.id}`)}
          >
            <RefreshCw className="w-3 h-3" />
            Retry in Builder
          </Button>
        </div>
      )}

      {/* Action buttons for completed projects */}
      {project.status === "completed" && (
        <div className="space-y-2">
          <div className="flex gap-2">
            <Button 
              variant="outline" 
              size="sm" 
              className="flex-1 gap-1 text-xs"
              onClick={() => handleDownloadReactNative(project)}
            >
              <Code className="w-3 h-3" />
              React Native
            </Button>
            <Button 
              variant="outline" 
              size="sm" 
              className="flex-1 gap-1 text-xs"
              onClick={() => handleDownloadBackend(project)}
            >
              <Server className="w-3 h-3" />
              Backend
            </Button>
          </div>
          <div className="flex gap-2">
            <Button 
              variant="outline" 
              size="sm" 
              className="flex-1 gap-1 text-xs"
              onClick={() => handleOpenExpoSnack(project)}
            >
              <ExternalLink className="w-3 h-3" />
              Live Preview
            </Button>
            <Button 
              variant="gradient" 
              size="sm" 
              className="flex-1 gap-1 text-xs"
              onClick={() => handleDownloadComplete(project)}
            >
              <Package className="w-3 h-3" />
              All
            </Button>
          </div>
          <div className="flex gap-2 pt-1">
            <Button 
              variant="ghost" 
              size="sm" 
              className="flex-1 gap-1 text-xs text-muted-foreground"
              onClick={() => toast.info("Play Store publishing coming soon!")}
            >
              <Play className="w-3 h-3" />
              Play Store
            </Button>
            <Button 
              variant="ghost" 
              size="sm" 
              className="flex-1 gap-1 text-xs text-muted-foreground"
              onClick={() => toast.info("App Store publishing coming soon!")}
            >
              <Apple className="w-3 h-3" />
              App Store
            </Button>
          </div>
        </div>
      )}
    </div>
  );

  return (
    <div className="min-h-screen bg-background">
      {/* Header */}
      <header className="border-b border-border/50 px-6 py-4">
        <div className="max-w-7xl mx-auto flex items-center justify-between">
          <Link to="/">
            <Logo size="sm" />
          </Link>

          <div className="flex items-center gap-4">
            {/* Credits Display */}
            <Button 
              variant="outline" 
              size="sm"
              onClick={() => navigate("/pricing")}
              className="gap-2"
            >
              <CreditCard className="w-4 h-4" />
              {creditsLoading ? (
                <Loader2 className="w-4 h-4 animate-spin" />
              ) : (
                <span className="font-medium">{balance} Credits</span>
              )}
            </Button>

            {/* Import Figma */}
            <Button 
              variant="outline" 
              size="sm"
              onClick={() => setFigmaDialogOpen(true)}
              className="gap-2"
            >
              <FileUp className="w-4 h-4" />
              <span className="hidden sm:inline">Import Figma</span>
            </Button>

            <DropdownMenu>
              <DropdownMenuTrigger asChild>
                <Button variant="ghost" size="icon" className="rounded-full">
                  <div className="w-8 h-8 rounded-full bg-gradient-primary flex items-center justify-center text-primary-foreground text-sm font-medium">
                    {getUserInitials()}
                  </div>
                </Button>
              </DropdownMenuTrigger>
              <DropdownMenuContent align="end" className="w-56">
                <div className="px-3 py-2">
                  <p className="font-medium text-foreground">{user?.name || "User"}</p>
                  <p className="text-sm text-muted-foreground">{user?.email || "user@example.com"}</p>
                </div>
                <DropdownMenuSeparator />
                <DropdownMenuItem>
                  <User className="w-4 h-4 mr-2" />
                  Profile
                </DropdownMenuItem>
                <DropdownMenuItem>
                  <Settings className="w-4 h-4 mr-2" />
                  Settings
                </DropdownMenuItem>
                <DropdownMenuItem onClick={() => navigate("/pricing")}>
                  <CreditCard className="w-4 h-4 mr-2" />
                  Buy Credits
                </DropdownMenuItem>
                <DropdownMenuSeparator />
                <DropdownMenuItem onClick={handleSignOut} className="text-destructive">
                  <LogOut className="w-4 h-4 mr-2" />
                  Sign out
                </DropdownMenuItem>
              </DropdownMenuContent>
            </DropdownMenu>
          </div>
        </div>
      </header>

      {/* Main content */}
      <main className="max-w-7xl mx-auto px-6 py-8">
        {/* Welcome section */}
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 mb-8">
          <div>
            <h1 className="text-2xl font-bold text-foreground">
              Welcome back{user?.name ? `, ${user.name.split(" ")[0]}` : ""}
            </h1>
            <p className="text-muted-foreground">Manage your mobile app projects</p>
          </div>
          <Button variant="gradient" onClick={() => navigate("/builder")} className="gap-2">
            <Plus className="w-4 h-4" />
            Create New App
          </Button>
        </div>

        {/* Stats */}
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 mb-8">
          <div className="p-5 rounded-xl border border-border bg-card/30 hover:bg-card/50 transition-colors">
            <div className="flex items-center gap-3">
              <div className="w-10 h-10 rounded-lg bg-primary/10 flex items-center justify-center">
                <FolderOpen className="w-5 h-5 text-primary" />
              </div>
              <div>
                {projectsLoading ? (
                  <Loader2 className="w-6 h-6 animate-spin text-primary" />
                ) : (
                  <p className="text-2xl font-bold text-foreground">{projects.length}</p>
                )}
                <p className="text-sm text-muted-foreground">Total Projects</p>
              </div>
            </div>
          </div>
          <div className="p-5 rounded-xl border border-border bg-card/30 hover:bg-card/50 transition-colors">
            <div className="flex items-center gap-3">
              <div className="w-10 h-10 rounded-lg bg-green-500/10 flex items-center justify-center">
                <Check className="w-5 h-5 text-green-500" />
              </div>
              <div>
                {projectsLoading ? (
                  <Loader2 className="w-6 h-6 animate-spin text-green-500" />
                ) : (
                  <p className="text-2xl font-bold text-foreground">{completedProjects.length}</p>
                )}
                <p className="text-sm text-muted-foreground">Ready to Download</p>
              </div>
            </div>
          </div>
          <div className="p-5 rounded-xl border border-border bg-card/30 hover:bg-card/50 transition-colors">
            <div className="flex items-center gap-3">
              <div className="w-10 h-10 rounded-lg bg-yellow-500/10 flex items-center justify-center">
                <Clock className="w-5 h-5 text-yellow-500" />
              </div>
              <div>
                {projectsLoading ? (
                  <Loader2 className="w-6 h-6 animate-spin text-yellow-500" />
                ) : (
                  <p className="text-2xl font-bold text-foreground">{buildingProjects.length}</p>
                )}
                <p className="text-sm text-muted-foreground">Building</p>
              </div>
            </div>
          </div>
        </div>

        {/* Projects grid */}
        <div>
          <div className="flex items-center justify-between mb-4">
            <h2 className="text-lg font-semibold text-foreground">Your Apps</h2>
            <Button 
              variant="ghost" 
              size="sm" 
              onClick={() => refetch()}
              className="gap-2"
            >
              <RefreshCw className="w-4 h-4" />
              Refresh
            </Button>
          </div>
          
          {projectsLoading ? (
            <div className="flex items-center justify-center py-12">
              <Loader2 className="w-8 h-8 animate-spin text-primary" />
            </div>
          ) : (
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
              {projects.length === 0 ? (
                renderEmptyState()
              ) : (
                <>
                  {projects.map(renderProjectCard)}

                  {/* New project card */}
                  <button
                    onClick={() => navigate("/builder")}
                    className="p-5 rounded-xl border border-dashed border-border hover:border-primary/50 flex flex-col items-center justify-center gap-3 min-h-[280px] transition-colors group"
                  >
                    <div className="w-12 h-12 rounded-xl bg-muted group-hover:bg-primary/10 flex items-center justify-center transition-colors">
                      <Plus className="w-6 h-6 text-muted-foreground group-hover:text-primary transition-colors" />
                    </div>
                    <span className="text-sm text-muted-foreground group-hover:text-foreground transition-colors">
                      Create New App
                    </span>
                  </button>
                </>
              )}
            </div>
          )}
        </div>
      </main>

      {/* Figma Import Dialog */}
      <Dialog open={figmaDialogOpen} onOpenChange={setFigmaDialogOpen}>
        <DialogContent className="sm:max-w-md">
          <DialogHeader>
            <DialogTitle>Import from Figma</DialogTitle>
            <DialogDescription>
              Paste your Figma file URL to import designs and convert them into a mobile app.
            </DialogDescription>
          </DialogHeader>
          <div className="space-y-4 py-4">
            <div className="space-y-2">
              <Label htmlFor="figma-url">Figma File URL</Label>
              <Input
                id="figma-url"
                placeholder="https://www.figma.com/file/..."
                value={figmaUrl}
                onChange={(e) => setFigmaUrl(e.target.value)}
              />
            </div>
            <div className="p-4 rounded-lg bg-muted/50 border border-border">
              <p className="text-sm text-muted-foreground">
                <span className="font-medium text-foreground">Coming Soon!</span> Figma import is currently under development. You'll be able to convert your Figma designs directly into functional mobile apps.
              </p>
            </div>
          </div>
          <div className="flex justify-end gap-2">
            <Button variant="outline" onClick={() => setFigmaDialogOpen(false)}>
              Cancel
            </Button>
            <Button variant="gradient" onClick={handleFigmaImport}>
              Import
            </Button>
          </div>
        </DialogContent>
      </Dialog>

      {/* Delete Confirmation Dialog */}
      <AlertDialog open={deleteDialogOpen} onOpenChange={setDeleteDialogOpen}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>Delete {projectToDelete?.name}?</AlertDialogTitle>
            <AlertDialogDescription>
              This action cannot be undone. This will permanently delete your app and all associated code.
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel disabled={isDeleting}>Cancel</AlertDialogCancel>
            <AlertDialogAction 
              onClick={handleDeleteProject}
              disabled={isDeleting}
              className="bg-destructive text-destructive-foreground hover:bg-destructive/90"
            >
              {isDeleting ? <Loader2 className="w-4 h-4 animate-spin mr-2" /> : null}
              Delete
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </div>
  );
};

export default Dashboard;