// App Templates for Different App Types

import { AppTemplate, ColorTheme } from './types';

const defaultThemes: Record<string, ColorTheme> = {
  'food-delivery': {
    primary: '#FF5722',
    secondary: '#FFC107',
    accent: '#4CAF50',
    background: '#FFFFFF',
    text: '#212121',
  },
  'ecommerce': {
    primary: '#3F51B5',
    secondary: '#FF4081',
    accent: '#00BCD4',
    background: '#FAFAFA',
    text: '#333333',
  },
  'social': {
    primary: '#E91E63',
    secondary: '#9C27B0',
    accent: '#03A9F4',
    background: '#F5F5F5',
    text: '#1A1A1A',
  },
  'booking': {
    primary: '#009688',
    secondary: '#FF9800',
    accent: '#2196F3',
    background: '#FFFFFF',
    text: '#263238',
  },
  'fitness': {
    primary: '#8BC34A',
    secondary: '#FF5722',
    accent: '#00BCD4',
    background: '#F9FBE7',
    text: '#33691E',
  },
  'travel': {
    primary: '#2196F3',
    secondary: '#FF9800',
    accent: '#4CAF50',
    background: '#E3F2FD',
    text: '#0D47A1',
  },
  'education': {
    primary: '#673AB7',
    secondary: '#FF5722',
    accent: '#4CAF50',
    background: '#F3E5F5',
    text: '#311B92',
  },
  'healthcare': {
    primary: '#00BCD4',
    secondary: '#4CAF50',
    accent: '#FF9800',
    background: '#E0F7FA',
    text: '#006064',
  },
};

export const appTemplates: Record<string, AppTemplate> = {
  'food-delivery': {
    type: 'food-delivery',
    name: 'Food Delivery App',
    description: 'Complete food ordering and delivery platform',
    screens: [
      'Splash',
      'Onboarding',
      'Login',
      'Signup',
      'Home',
      'RestaurantList',
      'RestaurantDetail',
      'Menu',
      'Cart',
      'Checkout',
      'OrderTracking',
      'OrderHistory',
      'Profile',
      'EditProfile',
      'Addresses',
      'Favorites',
      'Search',
      'Notifications',
    ],
    features: {
      login: { required: true, screens: ['Login', 'Signup', 'ForgotPassword'] },
      payment: { required: true, integration: 'Razorpay', dependencies: ['react-native-razorpay'] },
      maps: { required: true, integration: 'Google Maps', dependencies: ['react-native-maps'] },
      notifications: { required: false, integration: 'Firebase', dependencies: ['@react-native-firebase/messaging'] },
      chat: { required: false, integration: 'Socket.io', dependencies: ['socket.io-client'] },
      search: { required: true },
      favorites: { required: true },
      reviews: { required: true },
    },
    backend: {
      models: ['User', 'Restaurant', 'MenuItem', 'Order', 'Review', 'Address', 'Cart', 'Favorite'],
      endpoints: [
        '/auth/signup',
        '/auth/login',
        '/auth/logout',
        '/auth/forgot-password',
        '/restaurants',
        '/restaurants/:id',
        '/restaurants/:id/menu',
        '/cart',
        '/orders',
        '/orders/:id',
        '/payments/create-order',
        '/payments/verify',
        '/reviews',
        '/addresses',
        '/favorites',
      ],
      middleware: ['auth', 'validation', 'errorHandler', 'rateLimiter'],
    },
    defaultTheme: defaultThemes['food-delivery'],
  },

  'ecommerce': {
    type: 'ecommerce',
    name: 'E-Commerce App',
    description: 'Full-featured online shopping platform',
    screens: [
      'Splash',
      'Onboarding',
      'Login',
      'Signup',
      'Home',
      'Categories',
      'ProductList',
      'ProductDetail',
      'Cart',
      'Wishlist',
      'Checkout',
      'OrderConfirmation',
      'OrderHistory',
      'OrderDetail',
      'Profile',
      'EditProfile',
      'Addresses',
      'Search',
      'Filters',
      'Notifications',
    ],
    features: {
      login: { required: true, screens: ['Login', 'Signup', 'ForgotPassword'] },
      payment: { required: true, integration: 'Razorpay', dependencies: ['react-native-razorpay'] },
      notifications: { required: false, integration: 'Firebase', dependencies: ['@react-native-firebase/messaging'] },
      search: { required: true },
      favorites: { required: true },
      reviews: { required: true },
      'social-share': { required: false, dependencies: ['react-native-share'] },
    },
    backend: {
      models: ['User', 'Product', 'Category', 'Order', 'OrderItem', 'Review', 'Address', 'Cart', 'Wishlist'],
      endpoints: [
        '/auth/signup',
        '/auth/login',
        '/auth/logout',
        '/categories',
        '/products',
        '/products/:id',
        '/cart',
        '/wishlist',
        '/orders',
        '/orders/:id',
        '/payments/create-order',
        '/payments/verify',
        '/reviews',
        '/addresses',
      ],
      middleware: ['auth', 'validation', 'errorHandler', 'rateLimiter'],
    },
    defaultTheme: defaultThemes['ecommerce'],
  },

  'social': {
    type: 'social',
    name: 'Social Media App',
    description: 'Social networking platform with posts and messaging',
    screens: [
      'Splash',
      'Onboarding',
      'Login',
      'Signup',
      'Feed',
      'CreatePost',
      'PostDetail',
      'Profile',
      'EditProfile',
      'UserProfile',
      'Followers',
      'Following',
      'Messages',
      'Chat',
      'Search',
      'Explore',
      'Notifications',
      'Settings',
    ],
    features: {
      login: { required: true, screens: ['Login', 'Signup', 'ForgotPassword'] },
      chat: { required: true, integration: 'Socket.io', dependencies: ['socket.io-client'] },
      notifications: { required: true, integration: 'Firebase', dependencies: ['@react-native-firebase/messaging'] },
      camera: { required: true, dependencies: ['react-native-camera', 'react-native-image-picker'] },
      search: { required: true },
      'social-share': { required: true, dependencies: ['react-native-share'] },
    },
    backend: {
      models: ['User', 'Post', 'Comment', 'Like', 'Follow', 'Message', 'Conversation', 'Notification'],
      endpoints: [
        '/auth/signup',
        '/auth/login',
        '/auth/logout',
        '/users/:id',
        '/users/:id/followers',
        '/users/:id/following',
        '/posts',
        '/posts/:id',
        '/posts/:id/comments',
        '/posts/:id/likes',
        '/messages',
        '/conversations',
        '/notifications',
      ],
      middleware: ['auth', 'validation', 'errorHandler', 'rateLimiter', 'upload'],
    },
    defaultTheme: defaultThemes['social'],
  },

  'booking': {
    type: 'booking',
    name: 'Booking App',
    description: 'Service booking and appointment scheduling',
    screens: [
      'Splash',
      'Onboarding',
      'Login',
      'Signup',
      'Home',
      'ServiceList',
      'ServiceDetail',
      'ProviderList',
      'ProviderDetail',
      'SelectDateTime',
      'BookingConfirmation',
      'MyBookings',
      'BookingDetail',
      'Profile',
      'EditProfile',
      'Search',
      'Notifications',
    ],
    features: {
      login: { required: true, screens: ['Login', 'Signup', 'ForgotPassword'] },
      payment: { required: true, integration: 'Razorpay', dependencies: ['react-native-razorpay'] },
      notifications: { required: true, integration: 'Firebase', dependencies: ['@react-native-firebase/messaging'] },
      maps: { required: false, integration: 'Google Maps', dependencies: ['react-native-maps'] },
      search: { required: true },
      reviews: { required: true },
    },
    backend: {
      models: ['User', 'Service', 'Provider', 'Booking', 'TimeSlot', 'Review', 'Payment'],
      endpoints: [
        '/auth/signup',
        '/auth/login',
        '/auth/logout',
        '/services',
        '/services/:id',
        '/providers',
        '/providers/:id',
        '/providers/:id/availability',
        '/bookings',
        '/bookings/:id',
        '/payments/create-order',
        '/payments/verify',
        '/reviews',
      ],
      middleware: ['auth', 'validation', 'errorHandler', 'rateLimiter'],
    },
    defaultTheme: defaultThemes['booking'],
  },

  'fitness': {
    type: 'fitness',
    name: 'Fitness App',
    description: 'Workout tracking and fitness planning',
    screens: [
      'Splash',
      'Onboarding',
      'Login',
      'Signup',
      'Dashboard',
      'WorkoutList',
      'WorkoutDetail',
      'ActiveWorkout',
      'ExerciseDetail',
      'Progress',
      'Goals',
      'Nutrition',
      'MealPlan',
      'Profile',
      'EditProfile',
      'Settings',
      'Achievements',
    ],
    features: {
      login: { required: true, screens: ['Login', 'Signup', 'ForgotPassword'] },
      notifications: { required: true, integration: 'Firebase', dependencies: ['@react-native-firebase/messaging'] },
      analytics: { required: true },
      camera: { required: false, dependencies: ['react-native-camera', 'react-native-image-picker'] },
    },
    backend: {
      models: ['User', 'Workout', 'Exercise', 'WorkoutLog', 'Progress', 'Goal', 'Meal', 'Achievement'],
      endpoints: [
        '/auth/signup',
        '/auth/login',
        '/auth/logout',
        '/workouts',
        '/workouts/:id',
        '/exercises',
        '/workout-logs',
        '/progress',
        '/goals',
        '/meals',
        '/achievements',
      ],
      middleware: ['auth', 'validation', 'errorHandler'],
    },
    defaultTheme: defaultThemes['fitness'],
  },

  'travel': {
    type: 'travel',
    name: 'Travel App',
    description: 'Travel planning and booking platform',
    screens: [
      'Splash',
      'Onboarding',
      'Login',
      'Signup',
      'Home',
      'Explore',
      'DestinationDetail',
      'HotelList',
      'HotelDetail',
      'FlightSearch',
      'FlightList',
      'Booking',
      'BookingConfirmation',
      'MyTrips',
      'TripDetail',
      'Profile',
      'EditProfile',
      'Wishlist',
      'Search',
    ],
    features: {
      login: { required: true, screens: ['Login', 'Signup', 'ForgotPassword'] },
      payment: { required: true, integration: 'Razorpay', dependencies: ['react-native-razorpay'] },
      maps: { required: true, integration: 'Google Maps', dependencies: ['react-native-maps'] },
      notifications: { required: false, integration: 'Firebase', dependencies: ['@react-native-firebase/messaging'] },
      search: { required: true },
      favorites: { required: true },
      reviews: { required: true },
    },
    backend: {
      models: ['User', 'Destination', 'Hotel', 'Flight', 'Booking', 'Review', 'Wishlist', 'Trip'],
      endpoints: [
        '/auth/signup',
        '/auth/login',
        '/auth/logout',
        '/destinations',
        '/destinations/:id',
        '/hotels',
        '/hotels/:id',
        '/flights/search',
        '/bookings',
        '/bookings/:id',
        '/payments/create-order',
        '/payments/verify',
        '/trips',
        '/wishlist',
        '/reviews',
      ],
      middleware: ['auth', 'validation', 'errorHandler', 'rateLimiter'],
    },
    defaultTheme: defaultThemes['travel'],
  },

  'education': {
    type: 'education',
    name: 'Education App',
    description: 'Online learning and course platform',
    screens: [
      'Splash',
      'Onboarding',
      'Login',
      'Signup',
      'Home',
      'CourseList',
      'CourseDetail',
      'LessonList',
      'LessonPlayer',
      'Quiz',
      'QuizResult',
      'Progress',
      'Certificates',
      'Profile',
      'EditProfile',
      'MyLearning',
      'Search',
      'Bookmarks',
    ],
    features: {
      login: { required: true, screens: ['Login', 'Signup', 'ForgotPassword'] },
      payment: { required: false, integration: 'Razorpay', dependencies: ['react-native-razorpay'] },
      notifications: { required: true, integration: 'Firebase', dependencies: ['@react-native-firebase/messaging'] },
      search: { required: true },
      analytics: { required: true },
    },
    backend: {
      models: ['User', 'Course', 'Lesson', 'Quiz', 'Question', 'Progress', 'Certificate', 'Enrollment', 'Bookmark'],
      endpoints: [
        '/auth/signup',
        '/auth/login',
        '/auth/logout',
        '/courses',
        '/courses/:id',
        '/courses/:id/lessons',
        '/lessons/:id',
        '/quizzes/:id',
        '/progress',
        '/certificates',
        '/enrollments',
        '/bookmarks',
      ],
      middleware: ['auth', 'validation', 'errorHandler'],
    },
    defaultTheme: defaultThemes['education'],
  },

  'healthcare': {
    type: 'healthcare',
    name: 'Healthcare App',
    description: 'Telemedicine and health management',
    screens: [
      'Splash',
      'Onboarding',
      'Login',
      'Signup',
      'Home',
      'DoctorList',
      'DoctorDetail',
      'BookAppointment',
      'SelectDateTime',
      'AppointmentConfirmation',
      'MyAppointments',
      'AppointmentDetail',
      'VideoConsultation',
      'Prescriptions',
      'MedicalRecords',
      'Profile',
      'EditProfile',
      'HealthTracker',
    ],
    features: {
      login: { required: true, screens: ['Login', 'Signup', 'ForgotPassword'] },
      payment: { required: true, integration: 'Razorpay', dependencies: ['react-native-razorpay'] },
      notifications: { required: true, integration: 'Firebase', dependencies: ['@react-native-firebase/messaging'] },
      chat: { required: true, integration: 'Socket.io', dependencies: ['socket.io-client'] },
      camera: { required: true, dependencies: ['react-native-camera', 'react-native-webrtc'] },
    },
    backend: {
      models: ['User', 'Doctor', 'Appointment', 'Prescription', 'MedicalRecord', 'HealthMetric', 'Specialization'],
      endpoints: [
        '/auth/signup',
        '/auth/login',
        '/auth/logout',
        '/doctors',
        '/doctors/:id',
        '/doctors/:id/availability',
        '/appointments',
        '/appointments/:id',
        '/prescriptions',
        '/medical-records',
        '/health-metrics',
        '/payments/create-order',
        '/payments/verify',
      ],
      middleware: ['auth', 'validation', 'errorHandler', 'rateLimiter', 'hipaaCompliance'],
    },
    defaultTheme: defaultThemes['healthcare'],
  },
};

export function getTemplate(type: string): AppTemplate | undefined {
  return appTemplates[type];
}

export function detectAppType(conversation: string): string {
  const keywords: Record<string, string[]> = {
    'food-delivery': ['food', 'restaurant', 'delivery', 'order food', 'menu', 'cuisine', 'eat', 'dining'],
    'ecommerce': ['shop', 'store', 'buy', 'sell', 'product', 'cart', 'checkout', 'e-commerce', 'shopping'],
    'social': ['social', 'post', 'feed', 'follow', 'like', 'share', 'friends', 'network', 'community'],
    'booking': ['book', 'appointment', 'schedule', 'service', 'salon', 'spa', 'reservation'],
    'fitness': ['fitness', 'workout', 'exercise', 'gym', 'health', 'training', 'track', 'calories'],
    'travel': ['travel', 'hotel', 'flight', 'destination', 'trip', 'vacation', 'booking', 'tourism'],
    'education': ['learn', 'course', 'education', 'study', 'lesson', 'quiz', 'tutorial', 'class'],
    'healthcare': ['doctor', 'health', 'medical', 'appointment', 'prescription', 'telemedicine', 'patient'],
  };

  const lowerConversation = conversation.toLowerCase();
  let maxScore = 0;
  let detectedType = 'ecommerce'; // default

  for (const [type, words] of Object.entries(keywords)) {
    const score = words.filter(word => lowerConversation.includes(word)).length;
    if (score > maxScore) {
      maxScore = score;
      detectedType = type;
    }
  }

  return detectedType;
}

export function detectFeatures(conversation: string): string[] {
  const featureKeywords: Record<string, string[]> = {
    'login': ['login', 'signup', 'authentication', 'register', 'account'],
    'payment': ['payment', 'pay', 'checkout', 'razorpay', 'stripe', 'money', 'transaction'],
    'maps': ['map', 'location', 'gps', 'track', 'delivery tracking', 'directions'],
    'notifications': ['notification', 'push', 'alert', 'remind'],
    'chat': ['chat', 'message', 'conversation', 'real-time', 'support'],
    'camera': ['camera', 'photo', 'image', 'upload', 'scan'],
    'search': ['search', 'find', 'filter', 'browse'],
    'favorites': ['favorite', 'wishlist', 'save', 'bookmark'],
    'reviews': ['review', 'rating', 'feedback', 'comment'],
    'social-share': ['share', 'social', 'facebook', 'twitter', 'instagram'],
  };

  const lowerConversation = conversation.toLowerCase();
  const detectedFeatures: string[] = [];

  for (const [feature, keywords] of Object.entries(featureKeywords)) {
    if (keywords.some(keyword => lowerConversation.includes(keyword))) {
      detectedFeatures.push(feature);
    }
  }

  // Always include login
  if (!detectedFeatures.includes('login')) {
    detectedFeatures.push('login');
  }

  return detectedFeatures;
}
